/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CheckoutOfferIdRouteImport } from './routes/checkout.$offerId'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as SupplierIndexRouteImport } from './routes/supplier.index'
import { Route as SupplierAuctionsRouteImport } from './routes/supplier.auctions'
import { Route as SupplierOffersRouteImport } from './routes/supplier.offers'
import { Route as SupplierOrdersRouteImport } from './routes/supplier.orders'
import { Route as SupplierProfileRouteImport } from './routes/supplier.profile'
import { Route as SupplierOfferRequestIdRouteImport } from './routes/supplier.offer.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/admin/suppliers',
  path: '/admin/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOfferIdRoute = CheckoutOfferIdRouteImport.update({
  id: '/checkout/$offerId',
  path: '/checkout/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/supplier/',
  path: '/supplier/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierAuctionsRoute = SupplierAuctionsRouteImport.update({
  id: '/supplier/auctions',
  path: '/supplier/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierOffersRoute = SupplierOffersRouteImport.update({
  id: '/supplier/offers',
  path: '/supplier/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierOrdersRoute = SupplierOrdersRouteImport.update({
  id: '/supplier/orders',
  path: '/supplier/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierProfileRoute = SupplierProfileRouteImport.update({
  id: '/supplier/profile',
  path: '/supplier/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierOfferRequestIdRoute = SupplierOfferRequestIdRouteImport.update({
  id: '/supplier/offer/$requestId',
  path: '/supplier/offer/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/supplier/auctions': typeof SupplierAuctionsRoute
  '/supplier/offers': typeof SupplierOffersRoute
  '/supplier/orders': typeof SupplierOrdersRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/supplier/offer/$requestId': typeof SupplierOfferRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/supplier/auctions': typeof SupplierAuctionsRoute
  '/supplier/offers': typeof SupplierOffersRoute
  '/supplier/orders': typeof SupplierOrdersRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/supplier': typeof SupplierIndexRoute
  '/supplier/offer/$requestId': typeof SupplierOfferRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/supplier/auctions': typeof SupplierAuctionsRoute
  '/supplier/offers': typeof SupplierOffersRoute
  '/supplier/orders': typeof SupplierOrdersRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/supplier/offer/$requestId': typeof SupplierOfferRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/admin/orders'
    | '/admin/suppliers'
    | '/api/chat'
    | '/checkout/$offerId'
    | '/orders/$id'
    | '/requests/$id'
    | '/supplier/auctions'
    | '/supplier/offers'
    | '/supplier/orders'
    | '/supplier/profile'
    | '/admin/'
    | '/orders/'
    | '/requests/'
    | '/supplier/'
    | '/supplier/offer/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/admin/orders'
    | '/admin/suppliers'
    | '/api/chat'
    | '/checkout/$offerId'
    | '/orders/$id'
    | '/requests/$id'
    | '/supplier/auctions'
    | '/supplier/offers'
    | '/supplier/orders'
    | '/supplier/profile'
    | '/admin'
    | '/orders'
    | '/requests'
    | '/supplier'
    | '/supplier/offer/$requestId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/admin/orders'
    | '/admin/suppliers'
    | '/api/chat'
    | '/checkout/$offerId'
    | '/orders/$id'
    | '/requests/$id'
    | '/supplier/auctions'
    | '/supplier/offers'
    | '/supplier/orders'
    | '/supplier/profile'
    | '/admin/'
    | '/orders/'
    | '/requests/'
    | '/supplier/'
    | '/supplier/offer/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  ApiChatRoute: typeof ApiChatRoute
  CheckoutOfferIdRoute: typeof CheckoutOfferIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  RequestsIdRoute: typeof RequestsIdRoute
  SupplierAuctionsRoute: typeof SupplierAuctionsRoute
  SupplierOffersRoute: typeof SupplierOffersRoute
  SupplierOrdersRoute: typeof SupplierOrdersRoute
  SupplierProfileRoute: typeof SupplierProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  SupplierIndexRoute: typeof SupplierIndexRoute
  SupplierOfferRequestIdRoute: typeof SupplierOfferRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$offerId': {
      id: '/checkout/$offerId'
      path: '/checkout/$offerId'
      fullPath: '/checkout/$offerId'
      preLoaderRoute: typeof CheckoutOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/auctions': {
      id: '/supplier/auctions'
      path: '/supplier/auctions'
      fullPath: '/supplier/auctions'
      preLoaderRoute: typeof SupplierAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/offers': {
      id: '/supplier/offers'
      path: '/supplier/offers'
      fullPath: '/supplier/offers'
      preLoaderRoute: typeof SupplierOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/orders': {
      id: '/supplier/orders'
      path: '/supplier/orders'
      fullPath: '/supplier/orders'
      preLoaderRoute: typeof SupplierOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/profile': {
      id: '/supplier/profile'
      path: '/supplier/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof SupplierProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/offer/$requestId': {
      id: '/supplier/offer/$requestId'
      path: '/supplier/offer/$requestId'
      fullPath: '/supplier/offer/$requestId'
      preLoaderRoute: typeof SupplierOfferRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  ApiChatRoute: ApiChatRoute,
  CheckoutOfferIdRoute: CheckoutOfferIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  RequestsIdRoute: RequestsIdRoute,
  SupplierAuctionsRoute: SupplierAuctionsRoute,
  SupplierOffersRoute: SupplierOffersRoute,
  SupplierOrdersRoute: SupplierOrdersRoute,
  SupplierProfileRoute: SupplierProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  SupplierIndexRoute: SupplierIndexRoute,
  SupplierOfferRequestIdRoute: SupplierOfferRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
